### ISSUE TITLE
Brave wallet adapter gives "Signature verification failed"

### ISSUE THREAD

**Issue by AlexStefan** [solana-labs/wallet-adapter#478]
**Describe the bug**
Brave wallet adapter gives "Signature verification failed" when trying to send some transactions.

**To Reproduce**
I don't have the exact steps to reproduce the initial error (I don't understand what is the difference between the TX that works and the ones that don't), but if you try to sign a tx that doesn't have blockhash and fee payer assigned you would get "WalletSignTransactionError: Invalid parameters. at BraveWalletAdapter.signTransaction", while with Solflare for example you would get exact reason for the error "Error: Transaction recentBlockhash required".

**Expected behavior**
I would expect to not have to change anything in order to integrate Brave wallet adapter with a dApp.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser brave
 - Version 1.41.96

**Additional context**
Please take into account that the current way of sending transactions works with majority of wallet adapters: Phantom, Solflare, Slope, etc. For now this is blocking the integration of Brave wallet in our dApp.

**Comment by steveluscher** [comment]
The best way forward here is to find a transaction that triggers this problem, and to paste in the serialized transaction _before_ signing/sending.

On this line:

https://github.com/solana-labs/wallet-adapter/blob/master/packages/wallets/brave/src/adapter.ts#L173

…call `transaction.serialize()` and paste the result in a gist.github.com.

**Comment by AlexStefan** [comment]
@steveluscher sorry for the delay. See below my findings:
The place that you suggested is not where the TX is actually router through in neither of the cases. When you send a TX it goes through [signTransaction](https://github.com/solana-labs/wallet-adapter/blob/master/packages/wallets/brave/src/adapter.ts#L186) method. Calling the transaction.serialize() breaks the flow. The failing transactions are when creating TX for Quarry (there are more, but this would be most accessible I think).
If it helps I've made to SS with TX that works and TX that doesn't. First pic is from working TX, second is from not working one. 
<img width="550" alt="Screenshot 2022-07-24 at 21 57 51" src="https://user-images.githubusercontent.com/5895706/180662142-959c4ab5-697e-4058-a4f5-fb90516ccc40.png">
<img width="550" alt="Screenshot 2022-07-24 at 21 58 38" src="https://user-images.githubusercontent.com/5895706/180662146-f40a0ec2-7d14-40cb-af83-f1b2c37fab0e.png">

**Comment by AlexStefan** [comment]
@steveluscher any luck/findings?

**Comment by infosec-us-team** [comment]
I can't make offers on OpenSea because of this. Is there any fix?

**Comment by steveluscher** [comment]
If you disable signature verification on the `serialize` method then it will work. Take that non-working transaction and paste the serialized version of the transaction before and after into gist.github.com, using this:

```
transaction.serialize({
  requireAllSignatures: false,
  verifySignatures: false
})
```

**Comment by jordansexton** [comment]
What @steveluscher said. Also, please post actual code that produces an error rather than screenshots of the error in the console. We can't debug this with what's provided!

**Comment by AlexStefan** [comment]
> What @steveluscher said. Also, please post actual code that produces an error rather than screenshots of the error in the console. We can't debug this with what's provided!

https://gist.github.com/AlexStefan/56ec8446ae2b483fc6e136a6653ea4a2

I'm still not sure how the code that sends the TX helps. I've mentioned that this happens with Quarry SDK. 

 ```
let tx = new TransactionEnvelope(rewarder.sdk.provider, []);
if (miner && !(await quarry.provider.getAccountInfo(miner.minerKey))) {
  const { miner: minerKey, tx: createMinerTx } =
    await quarry.createMiner({});
  tx = createMinerTx;
}

if (miner) {
  tx = tx.combine(miner.stake(st.TokenAmount.parse(token, uiAmount)));
}

const { signature } = await tx.confirm();
```

**Comment by steveluscher** [comment]
Instead of copying and pasting the serialized transaction from the Chrome console (which produces weird truncations and other corruption) we need the _raw serialized bytearray_.

You can use the `copy()` feature of Chrome to copy this _directly_ to your clipboard.

```
copy(Array.from(transaction.serialize(...))) // Now it's on your clipboard and you can paste it into Gist.
```

**Comment by AlexStefan** [comment]
@steveluscher I've updated the gist

**Comment by SuperDzej** [comment]
Hi guys have same issue. Code worked 2 weeks ago, now it fails with `Phantom - RPC Error: Signature verification failed {code: -32003, message: 'Signature verification failed'}` . 

What it does is simple transaction with 2 instructions one to make associate token and second to transfer token from my wallet to another wallet where that new associate token was created

This are instructions

    **const instructions: TransactionInstruction[] = [];
    const mintPublicKey = new PublicKey(mint);
    // GET SOURCE ASSOCIATED ACCOUNT
    const associatedSourceTokenAddr: PublicKey = await getAssociatedTokenAddress(
        mintPublicKey,
        ownerKey
    );

    // GET DESTINATION ASSOCIATED ACCOUNT
    const associatedDestinationTokenAddr: PublicKey = await getAssociatedTokenAddress(
        mintPublicKey,
        destinationKey
    );
    console.info('Destination account', associatedDestinationTokenAddr.toBase58())
    const receiverAccount = await connection.getAccountInfo(
        associatedDestinationTokenAddr
    );

    if (receiverAccount === null) {
        console.log("Receiver account is null!");
        instructions.push(
            createAssociatedTokenAccountInstruction(
                destinationKey,
                associatedDestinationTokenAddr,
                destinationKey,
                mintPublicKey
            )
        );
    }

    instructions.push(
        createTransferCheckedInstruction(
            associatedSourceTokenAddr,
            mintPublicKey,
            associatedDestinationTokenAddr,
            ownerKey,
            1,
            0
        )
    );
    return instructions;**

**Comment by steveluscher** [comment]
Strange, @AlexStefan; I inspected your before/after transaction (they're identical other than the signature in the after transaction). Then, when I tried to verify the signature on the after transaction, it worked.

```
const beforeSigning = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 7, 12, 228, 86, 44, 2, 109, 84, 32, 119, 139, 40, 178, 69, 157, 69, 228, 133, 3, 145, 13, 17, 170, 50, 122, 199, 2, 201, 214, 124, 107, 78, 160, 75, 48, 150, 212, 138, 137, 93, 123, 86, 115, 165, 28, 49, 121, 89, 107, 44, 159, 154, 168, 187, 9, 106, 186, 123, 109, 217, 253, 157, 36, 76, 70, 31, 118, 165, 97, 194, 156, 246, 201, 217, 73, 28, 152, 146, 38, 214, 246, 184, 224, 189, 175, 16, 124, 240, 93, 136, 191, 244, 73, 145, 78, 106, 158, 255, 203, 33, 212, 240, 46, 124, 202, 235, 224, 164, 181, 218, 198, 114, 65, 106, 201, 45, 57, 24, 167, 148, 14, 19, 180, 116, 98, 35, 246, 110, 181, 119, 250, 139, 195, 4, 92, 120, 89, 129, 24, 160, 202, 71, 26, 166, 66, 105, 68, 77, 208, 148, 33, 5, 87, 220, 95, 57, 69, 247, 114, 40, 140, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89, 254, 99, 10, 31, 141, 60, 251, 207, 23, 164, 233, 241, 210, 230, 242, 55, 72, 134, 240, 154, 139, 228, 173, 214, 34, 7, 141, 82, 36, 63, 20, 74, 11, 98, 186, 7, 79, 114, 44, 157, 65, 20, 242, 216, 247, 10, 0, 198, 96, 2, 51, 123, 155, 249, 12, 135, 54, 87, 166, 210, 1, 219, 76, 128, 5, 251, 101, 4, 192, 83, 168, 3, 85, 170, 42, 109, 29, 132, 136, 158, 59, 112, 170, 15, 201, 192, 77, 188, 114, 232, 43, 26, 24, 244, 6, 90, 6, 167, 213, 23, 25, 44, 92, 81, 33, 140, 201, 76, 61, 74, 241, 127, 88, 218, 238, 8, 155, 161, 253, 68, 227, 219, 217, 138, 0, 0, 0, 0, 6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169, 122, 31, 55, 234, 168, 150, 2, 177, 55, 241, 65, 247, 145, 218, 178, 197, 127, 116, 173, 21, 208, 127, 172, 190, 194, 176, 156, 248, 163, 73, 176, 92, 3, 6, 7, 0, 2, 1, 8, 5, 11, 10, 0, 9, 9, 0, 1, 4, 7, 5, 0, 8, 2, 11, 8, 177, 242, 29, 176, 13, 217, 36, 71, 9, 7, 0, 1, 4, 2, 3, 11, 7, 16, 136, 126, 91, 162, 40, 131, 13, 127, 64, 66, 15, 0, 0, 0, 0, 0];
const afterSigning = [1, 235, 131, 165, 170, 38, 86, 190, 176, 230, 70, 85, 51, 83, 161, 236, 21, 210, 31, 54, 241, 19, 151, 108, 131, 70, 218, 233, 117, 212, 148, 234, 137, 16, 28, 54, 114, 150, 151, 244, 183, 76, 141, 144, 138, 231, 199, 247, 199, 69, 227, 63, 89, 25, 246, 199, 38, 45, 31, 36, 116, 55, 57, 104, 3, 1, 0, 7, 12, 228, 86, 44, 2, 109, 84, 32, 119, 139, 40, 178, 69, 157, 69, 228, 133, 3, 145, 13, 17, 170, 50, 122, 199, 2, 201, 214, 124, 107, 78, 160, 75, 48, 150, 212, 138, 137, 93, 123, 86, 115, 165, 28, 49, 121, 89, 107, 44, 159, 154, 168, 187, 9, 106, 186, 123, 109, 217, 253, 157, 36, 76, 70, 31, 118, 165, 97, 194, 156, 246, 201, 217, 73, 28, 152, 146, 38, 214, 246, 184, 224, 189, 175, 16, 124, 240, 93, 136, 191, 244, 73, 145, 78, 106, 158, 255, 203, 33, 212, 240, 46, 124, 202, 235, 224, 164, 181, 218, 198, 114, 65, 106, 201, 45, 57, 24, 167, 148, 14, 19, 180, 116, 98, 35, 246, 110, 181, 119, 250, 139, 195, 4, 92, 120, 89, 129, 24, 160, 202, 71, 26, 166, 66, 105, 68, 77, 208, 148, 33, 5, 87, 220, 95, 57, 69, 247, 114, 40, 140, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89, 254, 99, 10, 31, 141, 60, 251, 207, 23, 164, 233, 241, 210, 230, 242, 55, 72, 134, 240, 154, 139, 228, 173, 214, 34, 7, 141, 82, 36, 63, 20, 74, 11, 98, 186, 7, 79, 114, 44, 157, 65, 20, 242, 216, 247, 10, 0, 198, 96, 2, 51, 123, 155, 249, 12, 135, 54, 87, 166, 210, 1, 219, 76, 128, 5, 251, 101, 4, 192, 83, 168, 3, 85, 170, 42, 109, 29, 132, 136, 158, 59, 112, 170, 15, 201, 192, 77, 188, 114, 232, 43, 26, 24, 244, 6, 90, 6, 167, 213, 23, 25, 44, 92, 81, 33, 140, 201, 76, 61, 74, 241, 127, 88, 218, 238, 8, 155, 161, 253, 68, 227, 219, 217, 138, 0, 0, 0, 0, 6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169, 122, 31, 55, 234, 168, 150, 2, 177, 55, 241, 65, 247, 145, 218, 178, 197, 127, 116, 173, 21, 208, 127, 172, 190, 194, 176, 156, 248, 163, 73, 176, 92, 3, 6, 7, 0, 2, 1, 8, 5, 11, 10, 0, 9, 9, 0, 1, 4, 7, 5, 0, 8, 2, 11, 8, 177, 242, 29, 176, 13, 217, 36, 71, 9, 7, 0, 1, 4, 2, 3, 11, 7, 16, 136, 126, 91, 162, 40, 131, 13, 127, 64, 66, 15, 0, 0, 0, 0, 0];

const beforeTx = Transaction.from(beforeSigning);
const afterTx = Transaction.from(afterSigning);

console.log(beforeTx);
console.log(afterTx);

console.log('afterTx.verifySignatures', afterTx.verifySignatures());
```

Can you hop into `node_modules/@solana/web3.js/package.json` and tell me what the version number is?

**Comment by jordansexton** [comment]
Okay, let's maybe assume it's a problem with Brave Wallet or the Brave wallet adapter and process by elimination --

The Brave wallet adapter does this: https://github.com/solana-labs/wallet-adapter/blob/458f108fd43bc27de18c6883a0f235461a728f0c/packages/wallets/brave/src/adapter.ts#L168-L173

Can you try calling `window.braveSolana.signAndSendTransaction` directly with your transaction? If that works, it suggests a problem with the adapter's prep code.

**Comment by AlexStefan** [comment]
@jordansexton but as I mentioned, it is for sure a problem with Brave wallet adapter. This transaction goes through with Phantom/Solflare/Exodus and so on.

**Comment by jordansexton** [comment]
@SuperDzej please don't threadjack, this isn't the same issue. This isn't a place for general support questions, please use https://solana.stackexchange.com/

**Comment by jordansexton** [comment]
@AlexStefan the thing we're trying to determine is whether it's an issue with Brave Wallet _itself_ or the _wallet adapter_ for Brave Wallet. Other wallets are not relevant to this.

**Comment by AlexStefan** [comment]
Ok, so just to make sure I'm not doing something stupid, I switched

`const { signature } = await tx.confirm();`

to this 

`const { signature } = await window.braveSolana.signAndSendTransaction(tx);`

And I got the same error.

**Comment by jordansexton** [comment]
Okay, then it sounds like a problem with Brave Wallet on Solana (since it works with other wallets you tested, and the Brave adapter is out of the equation).

**Comment by jordansexton** [comment]
Also, what is `tx.confirm()` doing exactly?

**Comment by steveluscher** [comment]
I followed `tx.confirm()` down here:

https://github.com/saber-hq/saber-common/blob/master/packages/solana-contrib/src/transaction/TransactionEnvelope.ts#L367-L373

**Comment by jordansexton** [comment]
That method is not part of https://solana-labs.github.io/solana-web3.js/classes/Transaction.html. The adapter (and window.braveSolana.signAndSendTransaction expect a Solana web3.js Transaction object.

@AlexStefan what is `tx` here, a web3.js Transaction or something in this Saber lib?

**Comment by steveluscher** [comment]
> And I got the same error.

Cool! Can you post the stacktrace of that error; it might be useful to the Brave folks now that we have a serialized transaction, plus a stacktrace that results when you pass that to `window.braveSolana.signAndSendTransaction()`.

**Comment by steveluscher** [comment]
> const { signature } = await window.braveSolana.signAndSendTransaction(tx);

Also, @AlexStefan, make sure that you passed the web3.js `Transaction` object to that method, and not the Saber `TransactionEnvelope` object.

**Comment by AlexStefan** [comment]
Looking into it as I'm sending the envelope. ⏳

**Comment by AlexStefan** [comment]
> > const { signature } = await window.braveSolana.signAndSendTransaction(tx);
> 
> Also, @AlexStefan, make sure that you passed the web3.js `Transaction` object to that method, and not the Saber `TransactionEnvelope` object.

Ok, so I've done the following: 

```
const newTx = new anchor.web3.Transaction();
newTx.instructions = tx.instructions;
const { signature } = await window.braveSolana.signAndSendTransaction(newTx);
```

This is the stack trace of the error (do you know a better way to export this as well?):
<img width="539" alt="image" src="https://user-images.githubusercontent.com/5895706/181620807-2508ba3e-7766-4cde-a63c-50fca71e61af.png">

**Comment by jordansexton** [comment]
@AlexStefan Between Anchor libs, Saber libs, and whatever `QuaryContext` is, you have too much going on to confidently say where the error is coming from.

Please _greatly_ simplify the code you're testing to minimally reproduce that an error occurs with a `@solana/web3.js` Transaction object and `window.braveSolana.signAndSendTransaction`, only.

Otherwise I'm inclined to close this issue because there's nothing that tells me so far that this is an issue with the Brave wallet adapter, or even the Brave Wallet.

**Comment by AlexStefan** [comment]
> @AlexStefan Between Anchor libs, Saber libs, and whatever `QuaryContext` is, you have too much going on to confidently say where the error is coming from.
> 
> Please _greatly_ simplify the code you're testing to minimally reproduce that an error occurs with a `@solana/web3.js` Transaction object and `window.braveSolana.signAndSendTransaction`, only.
> 
> Otherwise I'm inclined to close this issue because there's nothing that tells me so far that this is an issue with the Brave wallet adapter, or even the Brave Wallet.

And what would be the issue if with all the other wallets it works?

**Comment by AlexStefan** [comment]
@jordansexton / @steveluscher if you check with the example from here: https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/example and try to Send the transaction with the already existing flow, you will encounter the same issue.

**Comment by jordansexton** [comment]
I just [tested this](https://github.com/solana-labs/wallet-adapter/commit/dcadeb3a7582548a751296d4893cbcf64d49e84e) with the example. However, the example uses devnet, and Brave Wallet's settings only allow Solana Mainnet to be selected. As such, the example can't be expected to work. Perhaps this is your issue, what network are you sending transactions on?

**Comment by jordansexton** [comment]
Ah, I switched to devnet and was able to replicate the issue. Working on it.

**Comment by jordansexton** [comment]
Okay, so it looks like if the transaction doesn’t have a `feePayer` or `recentBlockhash` set, it will fail without opening a transaction signing dialog on Brave.

Adding those, this code works:
```
const connection = new Connection(clusterApiUrl('devnet'));

const transaction = new Transaction().add(
    new TransactionInstruction({
        data: Buffer.from('Hello, world!'),
        keys: [],
        programId: new PublicKey('MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr'),
    })
);

transaction.feePayer = (window as any).braveSolana.publicKey;
transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;

const { signature } = await (window as any).braveSolana.signAndSendTransaction(transaction);
```

However, if we change this line to use optimistic confirmation, as is generally regarded as best practice, it fails:
```
transaction.recentBlockhash = (await connection.getLatestBlockhash('confirmed')).blockhash;
```

**Comment by jordansexton** [comment]
Fixed by https://github.com/solana-labs/wallet-adapter/pull/501

**Comment by AlexStefan** [comment]
Thank you guys for the assist! @steveluscher and @jordansexton 🙇‍♂️

**Comment by AlexStefan** [comment]
@jordansexton this is not fixed :( or maybe I still doing something stupid. Testing it with the wallet adapter example still throws the signature error.

**Comment by jordansexton** [comment]
The Brave adapter sets `preflightCommitment` from the Connection object now: https://github.com/solana-labs/wallet-adapter/blob/5437f957740e8651467b9eb74bf1d7ef77817f8f/packages/wallets/brave/src/adapter.ts#L168-L176

The base adapter uses the commitment set on the Connection object as well: https://github.com/solana-labs/wallet-adapter/blob/5437f957740e8651467b9eb74bf1d7ef77817f8f/packages/core/base/src/adapter.ts#L97

A dev from Brave tested with this branch and told me it worked, so we'll need to know what steps you're taking specifically.

Make sure you're cloning/pulling from the latest master, and running `yarn install` and `yarn build` from the project root before running the example, or you won't be running code with the fixes.

**Comment by AlexStefan** [comment]
@jordansexton I have not done anything special. Get latest on the [example repo](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/example) from wallet adapter (ran `yarn install` and `yarn build`), Connect to Brave and click the Send Transaction (devnet) button.

**Comment by jordansexton** [comment]
And just to check, this is with Brave Wallet configured to use Solana Devnet?

**Comment by AlexStefan** [comment]
> And just to check, this is with Brave Wallet configured to use Solana Devnet?

Yup

**Comment by yrliou** [comment]
FYI, I just pulled the latest master again, running yarn install and yarn build from the project root with this change in my local and confirmed it's still working.
```
diff --git a/packages/starter/example/components/ContextProvider.tsx b/packages/starter/example/components/ContextProvider.tsx
index 8b35f473..28398e46 100644
--- a/packages/starter/example/components/ContextProvider.tsx
+++ b/packages/starter/example/components/ContextProvider.tsx
@@ -6,7 +6,7 @@ import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
 import { WalletDialogProvider as MaterialUIWalletDialogProvider } from '@solana/wallet-adapter-material-ui';
 import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
 import { WalletModalProvider as ReactUIWalletModalProvider } from '@solana/wallet-adapter-react-ui';
-import { FakeWalletAdapter } from '@solana/wallet-adapter-wallets';
+import { BraveWalletAdapter } from '@solana/wallet-adapter-wallets';
 import { clusterApiUrl } from '@solana/web3.js';
 import { SnackbarProvider, useSnackbar } from 'notistack';
 import type { FC, ReactNode } from 'react';
@@ -67,7 +67,7 @@ const WalletContextProvider: FC<{ children: ReactNode }> = ({ children }) => {
              * will be compiled into your application, and only the dependencies of wallets that
              * your users connect to will be loaded.
              */
-            new FakeWalletAdapter(),
+            new BraveWalletAdapter(),
         ],
         []
     );
```

Please make sure you switch the network in Brave Wallet to Solana devnet first before trying to hit the example, otherwise you'll be trying to send transaction to mainnet with blockhash valid only on devnet.

<img width="330" alt="Screen Shot 2022-08-08 at 10 53 37 AM" src="https://user-images.githubusercontent.com/4730197/183482351-48a874c3-9ccf-4c91-bc86-7faa5a1bd71a.png">

<img width="1979" alt="Screen Shot 2022-08-08 at 10 45 00 AM" src="https://user-images.githubusercontent.com/4730197/183482382-3bfa484c-1832-4c86-9d88-0ac48e63b512.png">

**Comment by AlexStefan** [comment]
> FYI, I just pulled the latest master again, ran yarn install and yarn build from the project root with this change in my local, ran yarn dev from wallet-adapter/packages/starter/example and confirmed I can see the preflight commitment option being passed down, and can send out the transaction successfully.
> 
> ```
> diff --git a/packages/starter/example/components/ContextProvider.tsx b/packages/starter/example/components/ContextProvider.tsx
> index 8b35f473..28398e46 100644
> --- a/packages/starter/example/components/ContextProvider.tsx
> +++ b/packages/starter/example/components/ContextProvider.tsx
> @@ -6,7 +6,7 @@ import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
>  import { WalletDialogProvider as MaterialUIWalletDialogProvider } from '@solana/wallet-adapter-material-ui';
>  import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>  import { WalletModalProvider as ReactUIWalletModalProvider } from '@solana/wallet-adapter-react-ui';
> -import { FakeWalletAdapter } from '@solana/wallet-adapter-wallets';
> +import { BraveWalletAdapter } from '@solana/wallet-adapter-wallets';
>  import { clusterApiUrl } from '@solana/web3.js';
>  import { SnackbarProvider, useSnackbar } from 'notistack';
>  import type { FC, ReactNode } from 'react';
> @@ -67,7 +67,7 @@ const WalletContextProvider: FC<{ children: ReactNode }> = ({ children }) => {
>               * will be compiled into your application, and only the dependencies of wallets that
>               * your users connect to will be loaded.
>               */
> -            new FakeWalletAdapter(),
> +            new BraveWalletAdapter(),
>          ],
>          []
>      );
> ```
> 
> Please make sure you switch the network in Brave Wallet to Solana devnet first before trying to hit the example, otherwise you'll be trying to send transaction to mainnet with blockhash valid only on devnet which would get the same `Transaction simulation failed: Blockhash not found` error message from the RPC call.
> 
> Selected network should be Solana devnet: <img alt="Screen Shot 2022-08-08 at 10 53 37 AM" width="330" src="https://user-images.githubusercontent.com/4730197/183482351-48a874c3-9ccf-4c91-bc86-7faa5a1bd71a.png">
> 
> Commitment being passed down when hit `Send Transaction (devnet)`: <img alt="Screen Shot 2022-08-08 at 10 45 00 AM" width="1979" src="https://user-images.githubusercontent.com/4730197/183482382-3bfa484c-1832-4c86-9d88-0ac48e63b512.png">

I don't understand what is the difference, but I don't even get the Confirm modal. To make sure that the dApp has the right network, I've loaded the app after setting up devnet in wallet. Sign message works, request airdrop works.
For me it looks as below: 
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/5895706/183781520-659404d2-56a5-4d5a-a188-2b12333b0d6e.png">

**Comment by yrliou** [comment]
@AlexStefan I'm not sure if some fixes are only in 1.42.x and not in 1.41.96, but could you update to latest Brave release just in case?

**Comment by AlexStefan** [comment]
@yrliou just did it, no change :(

**Comment by yrliou** [comment]
@AlexStefan Ugh, and just to double check again because I'm currently out of ideas, you did do `yarn install` and `yarn build` under wallet-adapter folder instead of wallet-adapter/packages/starter/example right?

**Comment by AlexStefan** [comment]
> @AlexStefan Ugh, and just to double check again because I'm currently out of ideas, you did do `yarn install` and `yarn build` under wallet-adapter folder instead of wallet-adapter/packages/starter/example right?

Stupid, my bad! thank you for the effort and your time! Still need to figure things out on my end, but at least in the example works. Thank you again!
